### ISSUE TITLE
print statement in rocher.py

### ISSUE THREAD

**Issue by ChinDandekar** [julien-duponchelle/rocher#2]
Thank you so much for this package, it has been really good.

I am trying to use your package to render an IDE in the browser that might have to load medium sized files (~2-3MB). However, the print statement in _monaco_editor at line 64 prints out the entirety of the contents that I am trying to load, which slows down performance significantly. 

I was wondering if you could remove that line, as it greatly enhances the performance of the editor.

Thanks!

**Comment by julien-duponchelle** [comment]
Oh yes

**Comment by julien-duponchelle** [comment]
Should be fix in 0.48 can you confirm?

**Comment by ChinDandekar** [comment]
> Should be fix in 0.48 can you confirm?

Yes, it has been removed.

Thank you!
